// Sample data for initial development - based on real Mexican locations and data
import type {
  AirQualityStation,
  WaterQualityPoint,
  RecyclingCenter,
  PollutantCompany,
  Landfill,
  EnvironmentalComplaint,
} from "@/types";

export const sampleAirQuality: AirQualityStation[] = [
  {
    id: "aq-1",
    name: "Estación Pedregal",
    city: "Ciudad de México",
    state: "Ciudad de México",
    lat: 19.325,
    lng: -99.204,
    aqi: 72,
    pm25: 22,
    pm10: 45,
    o3: 38,
    no2: 25,
    so2: 8,
    co: 1.2,
    lastUpdated: "2026-03-15T10:00:00Z",
  },
  {
    id: "aq-2",
    name: "Estación Santa Fe",
    city: "Ciudad de México",
    state: "Ciudad de México",
    lat: 19.3573,
    lng: -99.2627,
    aqi: 85,
    pm25: 28,
    pm10: 52,
    o3: 45,
    no2: 32,
    so2: 12,
    co: 1.8,
    lastUpdated: "2026-03-15T10:00:00Z",
  },
  {
    id: "aq-3",
    name: "Estación Obispado",
    city: "Monterrey",
    state: "Nuevo León",
    lat: 25.6714,
    lng: -100.3386,
    aqi: 95,
    pm25: 35,
    pm10: 68,
    o3: 42,
    no2: 28,
    so2: 15,
    co: 2.1,
    lastUpdated: "2026-03-15T09:00:00Z",
  },
  {
    id: "aq-4",
    name: "Estación Tlaquepaque",
    city: "Guadalajara",
    state: "Jalisco",
    lat: 20.6362,
    lng: -103.3134,
    aqi: 68,
    pm25: 18,
    pm10: 42,
    o3: 35,
    no2: 22,
    so2: 6,
    co: 0.9,
    lastUpdated: "2026-03-15T10:00:00Z",
  },
  {
    id: "aq-5",
    name: "Estación Centro",
    city: "Puebla",
    state: "Puebla",
    lat: 19.0414,
    lng: -98.2063,
    aqi: 55,
    pm25: 15,
    pm10: 35,
    o3: 30,
    no2: 18,
    so2: 5,
    co: 0.7,
    lastUpdated: "2026-03-15T09:30:00Z",
  },
  {
    id: "aq-6",
    name: "Estación Cancún Centro",
    city: "Cancún",
    state: "Quintana Roo",
    lat: 21.1619,
    lng: -86.8515,
    aqi: 32,
    pm25: 8,
    pm10: 20,
    o3: 22,
    no2: 10,
    so2: 2,
    co: 0.4,
    lastUpdated: "2026-03-15T10:00:00Z",
  },
];

export const sampleWaterQuality: WaterQualityPoint[] = [
  {
    id: "wq-1",
    name: "Río Lerma - Toluca",
    river: "Río Lerma",
    state: "Estado de México",
    lat: 19.2826,
    lng: -99.6557,
    bod: 120,
    cod: 280,
    tss: 150,
    quality: "fuertemente_contaminada",
    lastUpdated: "2026-02-01",
  },
  {
    id: "wq-2",
    name: "Río Santiago - El Salto",
    river: "Río Santiago",
    state: "Jalisco",
    lat: 20.5176,
    lng: -103.1818,
    bod: 180,
    cod: 350,
    tss: 200,
    quality: "fuertemente_contaminada",
    lastUpdated: "2026-02-01",
  },
  {
    id: "wq-3",
    name: "Río Atoyac - Puebla",
    river: "Río Atoyac",
    state: "Puebla",
    lat: 18.9196,
    lng: -98.2471,
    bod: 95,
    cod: 200,
    tss: 120,
    quality: "contaminada",
    lastUpdated: "2026-02-15",
  },
  {
    id: "wq-4",
    name: "Río Grijalva - Villahermosa",
    river: "Río Grijalva",
    state: "Tabasco",
    lat: 17.9893,
    lng: -92.9475,
    bod: 45,
    cod: 100,
    tss: 80,
    quality: "contaminada",
    lastUpdated: "2026-02-10",
  },
  {
    id: "wq-5",
    name: "Río Tula - Hidalgo",
    river: "Río Tula",
    state: "Hidalgo",
    lat: 20.0543,
    lng: -99.3439,
    bod: 150,
    cod: 320,
    tss: 180,
    quality: "fuertemente_contaminada",
    lastUpdated: "2026-01-20",
  },
  {
    id: "wq-6",
    name: "Río Usumacinta - Tenosique",
    river: "Río Usumacinta",
    state: "Tabasco",
    lat: 17.4722,
    lng: -91.4228,
    bod: 12,
    cod: 30,
    tss: 25,
    quality: "buena",
    lastUpdated: "2026-02-20",
  },
];

export const sampleRecyclingCenters: RecyclingCenter[] = [
  {
    id: "rc-1",
    name: "Centro de Acopio ECOCE Polanco",
    address: "Av. Ejército Nacional 843, Polanco",
    city: "Ciudad de México",
    state: "Ciudad de México",
    lat: 19.4352,
    lng: -99.1936,
    materials: ["PET", "Cartón", "Aluminio", "Vidrio"],
    phone: "55-5280-3456",
    schedule: "Lun-Sáb 8:00-18:00",
  },
  {
    id: "rc-2",
    name: "Recicla Monterrey Centro",
    address: "Calle Zuazua 234, Centro",
    city: "Monterrey",
    state: "Nuevo León",
    lat: 25.6714,
    lng: -100.3097,
    materials: ["PET", "Cartón", "Papel", "Metales", "Electrónicos"],
    phone: "81-8345-6789",
    schedule: "Lun-Vie 9:00-17:00",
  },
  {
    id: "rc-3",
    name: "EcoAcopio Guadalajara",
    address: "Av. Vallarta 3222, Col. Vallarta",
    city: "Guadalajara",
    state: "Jalisco",
    lat: 20.6748,
    lng: -103.3897,
    materials: ["PET", "HDPE", "Cartón", "Vidrio", "Textiles"],
    phone: "33-3615-4321",
    schedule: "Lun-Sáb 7:00-19:00",
  },
  {
    id: "rc-4",
    name: "Centro Verde Querétaro",
    address: "Blvd. Bernardo Quintana 500",
    city: "Querétaro",
    state: "Querétaro",
    lat: 20.5881,
    lng: -100.3899,
    materials: ["PET", "Cartón", "Aluminio", "Aceite usado"],
    phone: "442-215-8900",
    schedule: "Lun-Vie 8:00-16:00",
  },
  {
    id: "rc-5",
    name: "Reciclaje Mérida Sur",
    address: "Calle 60 #234, Centro",
    city: "Mérida",
    state: "Yucatán",
    lat: 20.9674,
    lng: -89.6243,
    materials: ["PET", "Vidrio", "Cartón", "Orgánicos"],
    schedule: "Lun-Sáb 8:00-15:00",
  },
];

export const samplePollutantCompanies: PollutantCompany[] = [
  {
    id: "pc-1",
    name: "Refinería Tula",
    sector: "Petróleo y Gas",
    address: "Carretera México-Querétaro Km 148",
    municipality: "Tula de Allende",
    state: "Hidalgo",
    lat: 20.0543,
    lng: -99.3539,
    emissions: [
      { substance: "SO2", amount: 28500, unit: "ton/año", medium: "aire" },
      { substance: "NOx", amount: 12300, unit: "ton/año", medium: "aire" },
      { substance: "PM10", amount: 3200, unit: "ton/año", medium: "aire" },
    ],
    year: 2024,
  },
  {
    id: "pc-2",
    name: "Refinería Cadereyta",
    sector: "Petróleo y Gas",
    address: "Carretera Cadereyta-Allende Km 3",
    municipality: "Cadereyta Jiménez",
    state: "Nuevo León",
    lat: 25.5964,
    lng: -99.9833,
    emissions: [
      { substance: "SO2", amount: 22000, unit: "ton/año", medium: "aire" },
      { substance: "COV", amount: 8500, unit: "ton/año", medium: "aire" },
    ],
    year: 2024,
  },
  {
    id: "pc-3",
    name: "Cementera Cruz Azul Hidalgo",
    sector: "Cemento",
    address: "Ciudad Cooperativa Cruz Azul",
    municipality: "Tula de Allende",
    state: "Hidalgo",
    lat: 20.0843,
    lng: -99.3239,
    emissions: [
      { substance: "PM10", amount: 5600, unit: "ton/año", medium: "aire" },
      { substance: "CO2", amount: 1800000, unit: "ton/año", medium: "aire" },
      { substance: "NOx", amount: 4200, unit: "ton/año", medium: "aire" },
    ],
    year: 2024,
  },
  {
    id: "pc-4",
    name: "Termoeléctrica Tuxpan",
    sector: "Generación Eléctrica",
    address: "Carretera Tuxpan-Tampico Km 12",
    municipality: "Tuxpan",
    state: "Veracruz",
    lat: 21.0092,
    lng: -97.3842,
    emissions: [
      { substance: "CO2", amount: 4500000, unit: "ton/año", medium: "aire" },
      { substance: "SO2", amount: 15000, unit: "ton/año", medium: "aire" },
    ],
    year: 2024,
  },
];

export const sampleLandfills: Landfill[] = [
  {
    id: "lf-1",
    name: "Relleno Sanitario Bordo Poniente",
    type: "relleno_sanitario",
    municipality: "Ciudad de México",
    state: "Ciudad de México",
    lat: 19.4434,
    lng: -99.0214,
    capacity: 70000000,
    status: "clausurado",
  },
  {
    id: "lf-2",
    name: "Relleno Sanitario SIMEPRODE",
    type: "relleno_sanitario",
    municipality: "Salinas Victoria",
    state: "Nuevo León",
    lat: 25.9541,
    lng: -100.2961,
    capacity: 45000000,
    status: "activo",
  },
  {
    id: "lf-3",
    name: "Tiradero a Cielo Abierto Neza",
    type: "tiradero_cielo_abierto",
    municipality: "Nezahualcóyotl",
    state: "Estado de México",
    lat: 19.4003,
    lng: -99.0114,
    status: "clausurado",
  },
  {
    id: "lf-4",
    name: "Relleno Sanitario Picachos",
    type: "relleno_sanitario",
    municipality: "Zapopan",
    state: "Jalisco",
    lat: 20.7904,
    lng: -103.4413,
    capacity: 25000000,
    status: "activo",
  },
  {
    id: "lf-5",
    name: "Relleno Sanitario Cañada",
    type: "relleno_sanitario",
    municipality: "Querétaro",
    state: "Querétaro",
    lat: 20.5562,
    lng: -100.4438,
    capacity: 15000000,
    status: "activo",
  },
];

export const sampleComplaints: EnvironmentalComplaint[] = [
  {
    id: "ec-1",
    type: "Descarga de aguas residuales",
    description: "Empresa descargando aguas residuales sin tratamiento al Río Lerma",
    state: "Estado de México",
    municipality: "Lerma",
    lat: 19.2826,
    lng: -99.5157,
    status: "en_proceso",
    date: "2026-02-28",
    resource: "agua",
  },
  {
    id: "ec-2",
    type: "Emisiones atmosféricas",
    description: "Fábrica emitiendo humos negros sin control en zona industrial",
    state: "Nuevo León",
    municipality: "Apodaca",
    lat: 25.7814,
    lng: -100.1886,
    status: "recibida",
    date: "2026-03-10",
    resource: "aire",
  },
  {
    id: "ec-3",
    type: "Tiradero clandestino",
    description: "Acumulación de basura y residuos de construcción en terreno baldío",
    state: "Jalisco",
    municipality: "Tonalá",
    lat: 20.6232,
    lng: -103.2318,
    status: "concluida",
    date: "2026-01-15",
    resource: "suelo",
  },
  {
    id: "ec-4",
    type: "Tala ilegal",
    description: "Deforestación de zona boscosa protegida sin permisos",
    state: "Michoacán",
    municipality: "Uruapan",
    lat: 19.4171,
    lng: -102.0535,
    status: "en_proceso",
    date: "2026-03-01",
    resource: "forestal",
  },
];
